import { z } from "zod";
import { approveListing, createListingJob, exportListing, listingRequirements, listingRevisions, productFactsSchema, updateFacts, updateListing } from "../listing";
import { defineAction } from "./define";
import { slug } from "./products";
import { createFactsAssistJob, getFactsAssist } from "../facts-assistant";
import { ensureWorker } from "../jobs";

export const updateFactsAction = defineAction({ name: "update_product_facts", title: "Atualizar ficha", description: "Salva os fatos confirmados do produto. Campos ausentes continuam ausentes; alterar fatos torna anúncios anteriores desatualizados.", input: z.object({ slug, facts: productFactsSchema }), run: ({ slug, facts }) => updateFacts(slug, facts) });
export const generateListingAction = defineAction({ name: "generate_listing", title: "Gerar anúncio Shopee", description: "Enfileira o Codex para criar uma nova versão estruturada do anúncio Shopee a partir da ficha confirmada.", input: z.object({ slug, marketplace: z.literal("shopee").default("shopee") }), run: ({ slug }) => { const jobId = createListingJob(slug); ensureWorker(); return { jobId }; } });
export const listListingVersionsAction = defineAction({ name: "list_listing_versions", title: "Versões do anúncio", description: "Lista revisões salvas do anúncio Shopee e o checklist de preparação.", input: z.object({ slug }), readOnly: true, run: ({ slug }) => ({ revisions: listingRevisions(slug), requirements: listingRequirements(slug) }) });
export const editListingAction = defineAction({ name: "edit_listing", title: "Editar rascunho", description: "Preserva edições manuais de título, descrição e atributos em uma revisão do anúncio.", input: z.object({ slug, revisionId: z.string().uuid(), title: z.string().trim().min(1).max(120).optional(), description: z.string().trim().min(1).optional(), attributes: z.record(z.string(), z.string()).optional(), personalizationInstructions: z.string().optional(), categoryConfirmed: z.boolean().optional() }), run: ({ slug, revisionId, ...patch }) => updateListing(slug, revisionId, patch) });
export const validatePreparationAction = defineAction({ name: "validate_preparation", title: "Validar preparação", description: "Retorna a regra central de completude: ficha, categoria, imagens exportadas e pendências bloqueantes.", input: z.object({ slug }), readOnly: true, run: ({ slug }) => listingRequirements(slug) });
export const approveListingAction = defineAction({ name: "approve_listing", title: "Aprovar anúncio", description: "Aprova uma revisão atualizada depois da confirmação da categoria e sem pendências bloqueantes.", input: z.object({ slug, revisionId: z.string().uuid() }), run: ({ slug, revisionId }) => approveListing(slug, revisionId) });
export const exportListingAction = defineAction({ name: "export_listing", title: "Exportar anúncio", description: "Exporta título e descrição em TXT e os dados estruturados em JSON na pasta do produto.", input: z.object({ slug, revisionId: z.string().uuid() }), run: ({ slug, revisionId }) => exportListing(slug, revisionId) });
export const suggestProductFactsAction = defineAction({ name: "suggest_product_facts", title: "Preencher ficha com Codex", description: "Gera sugestões estruturadas para campos vazios usando as notas do vendedor e as fotos selecionadas. Sem seleção, usa uma única foto aprovada de fundo branco quando disponível.", input: z.object({ slug, prompt: z.string().max(5000).default(""), imageIds: z.array(z.number().int().positive()).max(4).optional() }), run: ({ slug, prompt, imageIds }) => { const result = createFactsAssistJob(slug, prompt, imageIds); ensureWorker(); return result; } });
export const getProductFactsSuggestionsAction = defineAction({ name: "get_product_facts_suggestions", title: "Ver sugestões da ficha", description: "Lê o resultado estruturado de um job de preenchimento assistido da ficha.", input: z.object({ slug, jobId: z.string().min(1) }), readOnly: true, run: ({ slug, jobId }) => getFactsAssist(slug, jobId) });
