"use client";
import { Check, Copy, Download, Save, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Alert, Badge, Button, Card, Field, Icon, SectionHeader, Spinner, Textarea } from "@/components/ui";
import { api, reportError } from "@/lib/client/api";
import type { ListingRevision } from "@/lib/listing";
import type { StepProps } from "./shared";
type Data = { revisions: ListingRevision[]; requirements: { missing: string[]; stale: boolean; hasExports: boolean; blocking: string[] } };
export function ListingStep({ product, reload }: StepProps) {
  const [data, setData] = useState<Data | null>(null); const [rev, setRev] = useState<ListingRevision | null>(null); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState<string | null>(null);
  const load = async () => { const d = await api<Data>(`/api/actions/list_listing_versions`, { method: "POST", json: { slug: product.slug } }); setData(d); setRev((old) => d.revisions.find((x) => x.id === old?.id) ?? d.revisions[0] ?? null); };
  useEffect(() => { load().catch(reportError); }, [product.slug]);
  async function generate() { setBusy(true); try { await api("/api/actions/generate_listing", { method: "POST", json: { slug: product.slug, marketplace: "shopee" } }); await reload(); } catch (e) { reportError(e); } finally { setBusy(false); } }
  async function save(extra: any = {}) { if (!rev) return; setBusy(true); try { await api("/api/actions/edit_listing", { method: "POST", json: { slug: product.slug, revisionId: rev.id, title: rev.manual.title ?? rev.title, description: rev.manual.description ?? rev.description, ...extra } }); await load(); } catch (e) { reportError(e); } finally { setBusy(false); } }
  async function copy(key: string, text: string) { try { await navigator.clipboard.writeText(text); setCopied(key); setTimeout(() => setCopied(null), 1800); } catch { reportError(new Error("Não foi possível copiar. Selecione o texto e copie manualmente.")); } }
  if (!data) return <Spinner/>;
  const text = rev ? { title: rev.manual.title ?? rev.title, description: rev.manual.description ?? rev.description } : null;
  return <div className="grid gap-8 lg:grid-cols-[1fr_320px]"><section className="space-y-6"><SectionHeader size="heading" title="Anúncio Shopee" description="O texto é um rascunho baseado apenas nos fatos confirmados. Você revisa e cadastra manualmente na Shopee." />
    {(data.requirements.missing.length || data.requirements.stale || data.requirements.blocking.length) && <Alert tone="warning">{data.requirements.stale ? "A ficha mudou; gere ou revise uma nova versão. " : ""}{data.requirements.missing.length ? `Ainda faltam: ${data.requirements.missing.join(", ")}. ` : ""}{data.requirements.blocking.join(" · ")}</Alert>}
    {!rev ? <Card className="space-y-4 p-6"><p className="text-ink-soft">Ainda não há versão de anúncio. Você pode gerar um rascunho mesmo com a ficha incompleta.</p><Button variant="primary" disabled={busy} onClick={generate}>{busy ? <Spinner/> : <Icon icon={Sparkles}/>} Gerar anúncio</Button></Card> : <>
      <div className="flex flex-wrap gap-2">{data.revisions.map((r) => <Button key={r.id} size="sm" variant={r.id === rev.id ? "primary" : "secondary"} onClick={() => setRev(r)}>Versão {r.createdAt.slice(0, 10)} {r.status === "approved" && "· aprovada"}</Button>)}</div>
      <Card className="space-y-4 p-5"><Field label="Título"><InputArea value={text!.title} onChange={(v) => setRev({ ...rev, manual: { ...rev.manual, title: v } })}/></Field><Button size="sm" variant="ghost" onClick={() => copy("title", text!.title)}><Icon icon={copied === "title" ? Check : Copy}/>{copied === "title" ? "Copiado" : "Copiar título"}</Button>
      {rev.titleAlternatives.length > 0 && <div className="space-y-2 text-sm">Alternativas:{rev.titleAlternatives.map((x) => <button key={x} className="block text-left text-ink-soft underline" onClick={() => setRev({ ...rev, manual: { ...rev.manual, title: x } })}>{x}</button>)}</div>}
      <Field label="Descrição"><Textarea rows={16} value={text!.description} onChange={(e) => setRev({ ...rev, manual: { ...rev.manual, description: e.target.value } })}/></Field><div className="flex gap-2"><Button onClick={() => save()} disabled={busy}><Icon icon={Save}/> Salvar alterações</Button><Button variant="ghost" onClick={() => copy("description", text!.description)}><Icon icon={copied === "description" ? Check : Copy}/> Copiar descrição</Button></div></Card>
      <Card className="space-y-3 p-5"><p><strong>Categoria sugerida:</strong> {rev.suggestedCategory.name}</p><p className="text-sm text-ink-soft">{rev.suggestedCategory.rationale}</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={rev.categoryConfirmed} onChange={(e) => save({ categoryConfirmed: e.target.checked })}/> Confirmo esta categoria para o cadastro</label><p className="text-xs text-ink-muted">É uma recomendação editorial, não um ID nem requisito oficial da Shopee.</p></Card>
      <Card className="space-y-3 p-5"><p className="font-medium">Pendências</p>{rev.pending.length ? rev.pending.map((p) => <p key={p.question}><Badge tone={p.blocking ? "warning" : "neutral"}>{p.blocking ? "bloqueia" : "revisar"}</Badge> {p.question}</p>) : <p className="text-ink-soft">Nenhuma pendência apontada.</p>}</Card>
    </>}</section><aside className="space-y-3 lg:sticky lg:top-20 lg:h-fit"><Button className="w-full" variant="secondary" disabled={busy} onClick={generate}><Icon icon={Sparkles}/> Nova versão</Button>{rev && <><Button className="w-full" variant="secondary" onClick={async () => { try { await api("/api/actions/export_listing", { method: "POST", json: { slug: product.slug, revisionId: rev.id } }); } catch (e) { reportError(e); }}}><Icon icon={Download}/> Exportar TXT e JSON</Button><Button className="w-full" variant="primary" disabled={busy} onClick={async () => { try { await api("/api/actions/approve_listing", { method: "POST", json: { slug: product.slug, revisionId: rev.id } }); await load(); } catch (e) { reportError(e); }}}><Icon icon={Check}/> Aprovar anúncio</Button></>}</aside></div>;
}
function InputArea({ value, onChange }: { value: string; onChange: (v: string) => void }) { return <input className="w-full rounded-input border border-line bg-surface px-3 py-2" value={value} onChange={(e) => onChange(e.target.value)} />; }
